# Generated by Django 2.1.1 on 2018-09-10 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_delete_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(default='', on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('mfa', models.BooleanField()),
                ('receive_emails', models.BooleanField()),
                ('location', models.CharField(max_length=264)),
                ('age', models.IntegerField()),
                ('owner', models.ForeignKey(default='', on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
