# Generated by Django 2.1.1 on 2018-09-12 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180911_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 14, 6, 244742), editable=False),
        ),
    ]
