# Generated by Django 2.1.1 on 2018-09-12 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180911_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 21, 2, 613189), editable=False),
        ),
    ]
