# Generated by Django 2.1.1 on 2018-09-12 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180911_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 24, 17, 432896), editable=False),
        ),
    ]
