# Generated by Django 2.1.1 on 2018-09-12 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180911_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 22, 43, 56, 926170), editable=False),
        ),
    ]
