# Generated by Django 2.1.1 on 2018-09-12 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20180911_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='message',
            new_name='notif_message',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='notif_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 22, 47, 10, 880973), editable=False),
        ),
    ]
