# Generated by Django 2.1.1 on 2018-09-12 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20180911_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notif_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 22, 58, 25, 496601), editable=False),
        ),
    ]
