# Generated by Django 2.1.1 on 2018-09-12 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20180911_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notif_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 23, 3, 25, 653864), editable=False),
        ),
    ]
