# Generated by Django 2.1.1 on 2018-09-12 04:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20180911_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notif_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 23, 39, 4, 603707), editable=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
