# Generated by Django 2.1.1 on 2018-09-12 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20180911_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notif_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 23, 51, 37, 114533), editable=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
