# Generated by Django 2.1.1 on 2018-09-12 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20180911_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='notif_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='notif_timestamp',
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 1, 1, 32, 660185), editable=False),
        ),
    ]
