# Generated by Django 2.1.1 on 2018-09-15 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180915_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
