# Generated by Django 2.1.1 on 2018-09-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180915_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
