# Generated by Django 2.1.1 on 2018-09-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usercalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercalendar',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserCalendar',
        ),
    ]
