# Generated by Django 2.1.1 on 2018-09-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180917_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
