# Generated by Django 2.1.1 on 2018-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180917_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
