# Generated by Django 2.1.1 on 2018-09-12 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(verbose_name='2018-09-11')),
                ('end_date', models.DateField(verbose_name='2018-09-11')),
                ('budget', models.IntegerField(default=0)),
                ('participants', models.IntegerField(default=1)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='travellog_pictures/')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'travel_log',
                'verbose_name_plural': 'travel_logs',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(verbose_name='2018-09-11')),
                ('end_date', models.DateField(verbose_name='2018-09-11')),
                ('budget', models.IntegerField()),
                ('participants', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trip_pictures/')),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
            },
        ),
        migrations.DeleteModel(
            name='AddVacationIdea',
        ),
    ]
