# Generated by Django 2.1.1 on 2018-09-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180909_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
