# Generated by Django 2.1.1 on 2018-09-10 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
        migrations.AddField(
            model_name='trips',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 9, 21, 5, 52, 458326)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='participants',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='user_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
