# Generated by Django 2.1.1 on 2018-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180911_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellogs',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='travellog_pictures'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trip_pictures'),
        ),
    ]
