# Generated by Django 2.1.1 on 2018-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180909_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(verbose_name='2018-09-09 21:26:34.884138'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trips',
            name='user_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
