# Generated by Django 2.1.1 on 2018-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180911_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellogs',
            name='end_date',
            field=models.DateField(verbose_name='2018-09-12'),
        ),
        migrations.AlterField(
            model_name='travellogs',
            name='start_date',
            field=models.DateField(verbose_name='2018-09-12'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateField(verbose_name='2018-09-12'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateField(verbose_name='2018-09-12'),
        ),
    ]
