# Generated by Django 2.1.1 on 2018-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180909_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(verbose_name='2018-09-09 23:38:39.970098'),
        ),
    ]
