# Generated by Django 2.1.1 on 2018-09-10 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180909_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='owner',
            field=models.ForeignKey(default='', on_delete='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(verbose_name='2018-09-10 00:47:30.847608'),
        ),
    ]
