# Generated by Django 2.1.1 on 2018-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180910_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='location',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='trips',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(verbose_name='2018-09-10 01:21:04.071227'),
        ),
    ]
