# Generated by Django 2.1.1 on 2018-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180910_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(verbose_name='2018-09-10 01:21:26.212187'),
        ),
    ]
