# Generated by Django 2.1.1 on 2018-09-10 07:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20180910_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(verbose_name='2018-09-10')),
                ('end_date', models.DateField(verbose_name='2018-09-10')),
                ('budget', models.IntegerField()),
                ('participants', models.IntegerField()),
                ('owner', models.ForeignKey(default='', on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='date',
        ),
        migrations.AddField(
            model_name='trips',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 9, 10), verbose_name='2018-09-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 9, 10), verbose_name='2018-09-10'),
            preserve_default=False,
        ),
    ]
