language: python
python:
  - 3.6
services:
  - memcached
  - postgresql
  - nginx
env:
  - DJANGO=2.1.1 DB=postgresql
install:
  - sudo apt-get install python3-dev
before_script:
  - sudo -u postgres psql -c "CREATE USER ayetravel_db_admin WITH PASSWORD 'ayetravel';"
  - sudo -u postgres psql -c "CREATE DATABASE ayetravel;"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ayetravel TO ayetravel_db_admin;"
  - sudo -u postgres psql -c "ALTER ROLE ayetravel_db_admin SET client_encoding TO 'utf8';"
  - sudo -u postgres psql -c "ALTER ROLE ayetravel_db_admin SET timezone TO 'UTC';"
  - systemctl start postgresql
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - cp $TRAVIS_BUILD_DIR/ayetravel-travis.conf /etc/nginx/sites-available/ayetravel-travis.conf
  - cd $TRAVIS_BUILD_DIR/__ayetravel__
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - gunicorn --daemon --workers 3 --bind unix:$TRAVIS_BUILD_DIR/__ayetravel__/ayetravel.sock ayetravel.wsgi && sudo systemctl start nginx
  #- python manage.py test
