# Generated by Django 2.1.1 on 2018-09-15 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travellogs', '0003_auto_20180915_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travellogs',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
