# Generated by Django 2.1.1 on 2018-09-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellogs', '0004_auto_20180915_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travellogs',
            old_name='participants_total',
            new_name='participants',
        ),
    ]
