version: '3'
services:
  cache:
     image: memcached
     container_name: ayetravel_cache
     restart: always
  db:
     image: postgres
     container_name: ayetravel_db
     restart: always
     environment:
        POSTGRES_PASSWORD: secret
  web:
     image: ciehanski/ayetravel
     build: ./webapp
     depends_on:
        - db
        - cache
     container_name: ayetravel_frontend
     restart: always
     ports:
        - "8080:80"
     command: bash -c "python manage.py migrate && python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
