# Generated by Django 2.1.1 on 2018-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trips',
            name='packing_list',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='trips',
            name='user_location',
            field=models.CharField(max_length=100),
        ),
    ]
