# Generated by Django 2.1.1 on 2018-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20180915_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='slug',
            field=models.SlugField(default='trip-slug', max_length=5, unique=True),
        ),
    ]
