# Generated by Django 2.1.1 on 2018-09-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20180916_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='participants_total',
        ),
    ]
