# Generated by Django 2.1.1 on 2018-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_trips_participants_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='comments_total',
            field=models.IntegerField(default=0),
        ),
    ]
