# Generated by Django 2.1.1 on 2018-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trips_comments_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='files',
            field=models.FilePathField(blank=True, null=True, path='trips/trip_files'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trips/trip_pictures'),
        ),
    ]
