# Generated by Django 2.1.1 on 2018-09-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20180916_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='likes',
        ),
    ]
